version: '3.9'
name: DEDALUS-italian-DT
services:
  comfort-flexibility-service:
    build: .
    container_name: comfort-flexibility-service
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"
    environment:
      DOMX_USERNAME: ${DOMX_USERNAME}
      DOMX_PASSWORD: ${DOMX_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      APP_PORT: ${APP_PORT}
      APP_FE_URL: ${APP_FE_URL}
      DB_PATH: /app/data/users.db
    volumes:
      - data:/app/data
    env_file:
      - .env
  scheduler:
    build: ./scheduler
    container_name: IT_DT_daily_trigger
    depends_on:
      - comfort-flexibility-service
    volumes:
      - .env:/env/.env
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped

volumes:
  data:
